input.onButtonPressed(Button.A, function () {
    xiamiBoard.motorRun(MOTOR.M1, DIRECTION.CW, 255)
    xiamiBoard.motorRun(MOTOR.M2, DIRECTION.CW, 255)
})
input.onButtonPressed(Button.B, function () {
    xiamiBoard.motorRun(MOTOR.M1, DIRECTION.CW, 0)
    xiamiBoard.motorRun(MOTOR.M2, DIRECTION.CW, 0)
})
basic.showIcon(IconNames.SmallHeart)
xiamiBoard.setBrightness(57)
xiamiBoard.initXiaMiBoard()
xiamiBoard.motorStop(MOTOR.M1)
xiamiBoard.motorStop(MOTOR.M2)
xiamiBoard.OLEDclear()
xiamiBoard.LED(1, 1, 1)
xiamiBoard.showColor(0x00ffff)
xiamiBoard.tempHumiInit(SENSOR.AHT20)
xiamiBoard.tempHumiInit(SENSOR.SHTC3)
basic.forever(function () {
    xiamiBoard.OLEDshowUserText("DFRobot", 0, 0)
    xiamiBoard.OLEDshowUserNumber(2024, 1, 0)
    xiamiBoard.OLEDshowUserNumber(xiamiBoard.readFlre(), 2, 0)
    xiamiBoard.OLEDshowUserNumber(xiamiBoard.readSensor(SENSOR.SHTC3, PARA.TEMP), 3, 0)
    xiamiBoard.OLEDshowUserNumber(xiamiBoard.readSensor(SENSOR.SHTC3, PARA.HUM), 4, 0)
    basic.pause(5000)
})
